# Generated by Django 4.2.7 on 2025-11-29 17:39

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('doctor_id', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('conclusion', models.CharField(blank=True, choices=[('healthy', 'Здоров'), ('unhealthy', 'Не здоров')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('examination_date', models.DateTimeField(auto_now_add=True)),
                ('doctor_signature', models.CharField(blank=True, max_length=255)),
                ('recommendations', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('clinic', 'Клиника'), ('employer', 'Работодатель')], max_length=20)),
                ('clinic_role', models.CharField(blank=True, choices=[('manager', 'Менеджер'), ('doctor', 'Врач'), ('profpathologist', 'Профпатолог'), ('receptionist', 'Регистратура')], max_length=20, null=True)),
                ('registration_completed', models.BooleanField(default=False)),
                ('registration_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='crm_user_set', related_query_name='crm_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='crm_user_set', related_query_name='crm_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RouteSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('iin', models.CharField(max_length=12)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('visit_date', models.DateField()),
                ('services', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_sheets', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('iin', models.CharField(max_length=12)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('doctor_conclusions', models.JSONField(default=list)),
                ('final_verdict', models.CharField(blank=True, choices=[('fit', 'Годен'), ('temporary_unfit', 'Временная непригодность'), ('permanent_unfit', 'Постоянная непригодность')], max_length=20, null=True)),
                ('verdict_date', models.DateTimeField(blank=True, null=True)),
                ('profpathologist_name', models.CharField(blank=True, max_length=255)),
                ('profpathologist_signature', models.CharField(blank=True, max_length=255)),
                ('temporary_unfit_until', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ContingentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('iin', models.CharField(max_length=12)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('harmful_factors', models.JSONField(default=list)),
                ('requires_examination', models.BooleanField(default=True)),
                ('last_examination_date', models.DateField(blank=True, null=True)),
                ('next_examination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contingent_employees', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_clinic', 'Ожидает утверждения клиникой'), ('pending_employer', 'Ожидает утверждения работодателем'), ('approved', 'Утвержден'), ('sent_to_ses', 'Отправлен в СЭС')], default='draft', max_length=20)),
                ('clinic_name', models.CharField(blank=True, max_length=255)),
                ('clinic_director', models.CharField(blank=True, max_length=255)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('employer_representative', models.CharField(blank=True, max_length=255)),
                ('ses_representative', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by_clinic_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_employer_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_ses_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_plans', to='api.user')),
            ],
        ),
    ]
