# Generated by Django 4.2.7 on 2025-12-10 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarplan',
            name='rejected_by_employer_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отклонения работодателем'),
        ),
        migrations.AddField(
            model_name='calendarplan',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Причина отклонения календарного плана работодателем', verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='contract',
            name='confirmed_by_employer_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения работодателем'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employer_rejection_reason',
            field=models.TextField(blank=True, help_text='Причина отклонения исполнения работодателем', verbose_name='Причина отклонения работодателем'),
        ),
        migrations.AddField(
            model_name='contract',
            name='executed_by_clinic_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отметки исполнения клиникой'),
        ),
        migrations.AddField(
            model_name='contract',
            name='execution_notes',
            field=models.TextField(blank=True, help_text='Примечания клиники при отметке исполнения', verbose_name='Примечания к исполнению'),
        ),
        migrations.AddField(
            model_name='contract',
            name='execution_type',
            field=models.CharField(blank=True, choices=[('full', 'Полное исполнение'), ('partial', 'Частичное исполнение')], help_text='Тип исполнения, указанный клиникой', max_length=20, null=True, verbose_name='Тип исполнения'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_subcontracted',
            field=models.BooleanField(default=False, help_text='Флаг указывающий что договор передан на субподряд', verbose_name='Передан на субподряд'),
        ),
        migrations.AddField(
            model_name='contract',
            name='original_clinic',
            field=models.ForeignKey(blank=True, help_text='Клиника, которая передала договор на субподряд', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontracted_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Оригинальная клиника'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subcontract_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия субподряда'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subcontract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма, которую основная клиника платит субподрядчику', max_digits=15, null=True, verbose_name='Сумма субподряда'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subcontract_rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отклонения субподряда'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subcontract_rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения субподряда'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subcontract_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], max_length=20, null=True, verbose_name='Статус субподряда'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subcontracted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата передачи на субподряд'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subcontractor_clinic',
            field=models.ForeignKey(blank=True, help_text='Клиника-субподрядчик, которая выполняет работу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontractor_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Клиника-субподрядчик'),
        ),
        migrations.AlterField(
            model_name='calendarplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_clinic', 'Ожидает утверждения клиникой'), ('pending_employer', 'Ожидает утверждения работодателем'), ('approved', 'Утвержден'), ('rejected', 'Отклонен работодателем'), ('sent_to_ses', 'Отправлен в СЭС')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='contracthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Создан'), ('updated', 'Обновлен'), ('sent_for_approval', 'Отправлен на согласование'), ('approved', 'Согласован'), ('rejected', 'Отклонен'), ('resent_for_approval', 'Повторно отправлен на согласование'), ('cancelled', 'Отменен'), ('executed', 'Исполнен'), ('subcontracted', 'Передан на субподряд'), ('employer_registered', 'Работодатель зарегистрировался')], max_length=30, verbose_name='Действие'),
        ),
    ]
