# Generated by Django 4.2.7 on 2025-11-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingentemployee',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='contingentemployee',
            name='position_experience_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стаж по занимаемой должности (лет)'),
        ),
        migrations.AddField(
            model_name='contingentemployee',
            name='quarter',
            field=models.CharField(blank=True, max_length=20, verbose_name='Квартал'),
        ),
        migrations.AddField(
            model_name='contingentemployee',
            name='total_experience_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общий стаж (лет)'),
        ),
        migrations.AlterField(
            model_name='contingentemployee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='contingentemployee',
            name='department',
            field=models.CharField(max_length=255, verbose_name='Объект или участок'),
        ),
        migrations.AlterField(
            model_name='contingentemployee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='contingentemployee',
            name='harmful_factors',
            field=models.JSONField(default=list, verbose_name='Профессиональная вредность'),
        ),
        migrations.AlterField(
            model_name='contingentemployee',
            name='iin',
            field=models.CharField(max_length=12, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='contingentemployee',
            name='last_examination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего медосмотра'),
        ),
        migrations.AlterField(
            model_name='contingentemployee',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='contingentemployee',
            name='next_examination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего осмотра'),
        ),
        migrations.AlterField(
            model_name='contingentemployee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contingentemployee',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Занимаемая должность'),
        ),
        migrations.AlterField(
            model_name='contingentemployee',
            name='requires_examination',
            field=models.BooleanField(default=True, verbose_name='Требуется осмотр'),
        ),
    ]
