# Generated by Django 4.2.7 on 2025-12-05 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_subcontracted',
            field=models.BooleanField(default=False, help_text='Флаг указывающий что договор передан на субподряд', verbose_name='Передан на субподряд'),
        ),
        migrations.AddField(
            model_name='contract',
            name='original_clinic',
            field=models.ForeignKey(blank=True, help_text='Клиника, которая передала договор на субподряд', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontracted_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Оригинальная клиника'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subcontracted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата передачи на субподряд'),
        ),
        # Примечание: если поле subcontracted_at уже существует, выполните:
        # python manage.py migrate api 0002 --fake
        migrations.AddField(
            model_name='contract',
            name='subcontractor_clinic',
            field=models.ForeignKey(blank=True, help_text='Клиника-субподрядчик, которая выполняет работу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontractor_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Клиника-субподрядчик'),
        ),
        migrations.AlterField(
            model_name='contracthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Создан'), ('updated', 'Обновлен'), ('sent_for_approval', 'Отправлен на согласование'), ('approved', 'Согласован'), ('rejected', 'Отклонен'), ('resent_for_approval', 'Повторно отправлен на согласование'), ('cancelled', 'Отменен'), ('executed', 'Исполнен'), ('subcontracted', 'Передан на субподряд')], max_length=30, verbose_name='Действие'),
        ),
    ]
