# Generated by Django 4.2.7 on 2025-12-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contract_is_subcontracted_contract_original_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='subcontract_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия субподряда'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subcontract_rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отклонения субподряда'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subcontract_rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения субподряда'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subcontract_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], max_length=20, null=True, verbose_name='Статус субподряда'),
        ),
    ]
