# Generated by Django 4.2.7 on 2025-12-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_calendarplan_rejected_by_employer_at_and_more'),
    ]

    operations = [
        # Добавляем индексы для оптимизации запросов
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_contingent_contract ON api_contingentemployee(contract_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_contingent_contract;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_contingent_user ON api_contingentemployee(user_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_contingent_user;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_calendar_plan_contract ON api_calendarplan(contract_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_calendar_plan_contract;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_route_sheet_patient ON api_routesheet(patient_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_route_sheet_patient;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_contract_employer ON api_contract(employer_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_contract_employer;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_contract_status ON api_contract(status);",
            reverse_sql="DROP INDEX IF EXISTS idx_contract_status;"
        ),
    ]
