# Generated by Django 4.2.7 on 2025-11-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contingentemployee_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingentemployee',
            name='iin',
            field=models.CharField(max_length=20, verbose_name='ИИН'),
        ),
    ]
