# Generated by Django 4.2.7 on 2025-12-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contract_subcontract_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='subcontract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма, которую основная клиника платит субподрядчику', max_digits=15, null=True, verbose_name='Сумма субподряда'),
        ),
    ]
