# Generated by Django 4.2.7 on 2025-12-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20251212_0209'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contingentemployee',
            index=models.Index(fields=['contract'], name='contingent_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='contingentemployee',
            index=models.Index(fields=['user'], name='contingent_user_idx'),
        ),
        migrations.AddIndex(
            model_name='contingentemployee',
            index=models.Index(fields=['contract', 'id'], name='contingent_contract_id_idx'),
        ),
    ]
