# Generated by Django 4.2.7 on 2025-11-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contingentemployee_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingentemployee',
            name='iin',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИИН'),
        ),
    ]
