# Generated by Django 4.2.7 on 2025-11-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contingentemployee_iin'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='health_group',
            field=models.CharField(blank=True, choices=[('1', 'Группа 1 - Здоровый'), ('2', 'Группа 2 - Практически здоровый'), ('3', 'Группа 3 - Имеет признаки воздействия ВПФ'), ('4', 'Группа 4 - Требует динамического наблюдения'), ('5', 'Группа 5 - Требует лечения'), ('6', 'Группа 6 - Требует реабилитации/профпатологии')], max_length=1, null=True, verbose_name='Группа здоровья'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='referral_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата направления'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='referral_sent',
            field=models.BooleanField(default=False, verbose_name='Направление отправлено'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='referral_type',
            field=models.CharField(blank=True, choices=[('rehabilitation', 'Реабилитация'), ('profpathology', 'Профпатология'), ('specialist', 'Узкий специалист')], max_length=50, verbose_name='Тип направления'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='requires_referral',
            field=models.BooleanField(default=False, verbose_name='Требуется направление'),
        ),
        migrations.CreateModel(
            name='RecommendationTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('recommendation', models.TextField(verbose_name='Рекомендация')),
                ('recommendation_type', models.CharField(choices=[('transfer', 'Перевод на другую работу'), ('treatment', 'Лечение'), ('observation', 'Динамическое наблюдение'), ('rehabilitation', 'Реабилитация')], max_length=50, verbose_name='Тип рекомендации')),
                ('status', models.CharField(choices=[('pending', 'Ожидает исполнения'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='HealthImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('plan_data', models.JSONField(default=dict, verbose_name='Данные плана')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_tsb', 'Ожидает согласования ТСБ/СЭБН'), ('approved', 'Утвержден')], default='draft', max_length=20)),
                ('approved_by_tsb_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_improvement_plans', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('iin', models.CharField(max_length=12)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('disease_type', models.CharField(max_length=255, verbose_name='Тип заболевания')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('doctor_name', models.CharField(max_length=255, verbose_name='Врач, выявивший заболевание')),
                ('sent_to_tsb', models.BooleanField(default=False, verbose_name='Отправлено в ТСБ/СЭБН')),
                ('sent_to_employer', models.BooleanField(default=False, verbose_name='Отправлено работодателю')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_notifications', to='api.user')),
            ],
        ),
    ]
