# Generated by Django 4.2.7 on 2025-12-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_old_is_subcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='confirmed_by_employer_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения работодателем'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employer_rejection_reason',
            field=models.TextField(blank=True, help_text='Причина отклонения исполнения работодателем', verbose_name='Причина отклонения работодателем'),
        ),
        migrations.AddField(
            model_name='contract',
            name='executed_by_clinic_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отметки исполнения клиникой'),
        ),
        migrations.AddField(
            model_name='contract',
            name='execution_notes',
            field=models.TextField(blank=True, help_text='Примечания клиники при отметке исполнения', verbose_name='Примечания к исполнению'),
        ),
        migrations.AddField(
            model_name='contract',
            name='execution_type',
            field=models.CharField(blank=True, choices=[('full', 'Полное исполнение'), ('partial', 'Частичное исполнение')], help_text='Тип исполнения, указанный клиникой', max_length=20, null=True, verbose_name='Тип исполнения'),
        ),
    ]
