# Generated by Django 4.2.7 on 2025-11-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cabinet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер кабинета'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_schedule',
            field=models.JSONField(default=dict, help_text='Формат: {"monday": {"start": "09:00", "end": "18:00"}, ...}', verbose_name='Расписание работы'),
        ),
    ]
