# Generated by Django 4.2.7 on 2025-11-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_doctor_cabinet_doctor_work_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('iin', models.CharField(max_length=12)),
                ('referral_type', models.CharField(choices=[('rehabilitation', 'Реабилитация'), ('profpathology', 'Профпатология'), ('specialist', 'Узкий специалист')], max_length=50, verbose_name='Тип направления')),
                ('target_organization', models.CharField(blank=True, max_length=255, verbose_name='Целевая организация')),
                ('reason', models.TextField(verbose_name='Причина направления')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('sent', 'Отправлено'), ('accepted', 'Принято'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='created', max_length=20, verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expertise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='api.expertise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='api.user')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('test_type', models.CharField(help_text='Например: Общий анализ крови, Биохимия и т.д.', max_length=255, verbose_name='Тип исследования')),
                ('test_name', models.CharField(max_length=255, verbose_name='Название анализа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='pending', max_length=20)),
                ('results', models.JSONField(default=dict, help_text='Структурированные результаты анализов', verbose_name='Результаты')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('performed_by', models.CharField(blank=True, max_length=255, verbose_name='Выполнил')),
                ('performed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_tests', to='api.routesheet')),
            ],
            options={
                'verbose_name': 'Лабораторное исследование',
                'verbose_name_plural': 'Лабораторные исследования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FunctionalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('test_type', models.CharField(help_text='Например: ЭКГ, Спирометрия, Рентген и т.д.', max_length=255, verbose_name='Тип исследования')),
                ('test_name', models.CharField(max_length=255, verbose_name='Название исследования')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='pending', max_length=20)),
                ('results', models.JSONField(default=dict, help_text='Структурированные результаты исследований', verbose_name='Результаты')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('performed_by', models.CharField(blank=True, max_length=255, verbose_name='Выполнил')),
                ('performed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functional_tests', to='api.routesheet')),
            ],
            options={
                'verbose_name': 'Функциональное исследование',
                'verbose_name_plural': 'Функциональные исследования',
                'ordering': ['-created_at'],
            },
        ),
    ]
