# Generated by Django 4.2.7 on 2025-11-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_referral_laboratorytest_functionaltest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255, verbose_name='ID пациента')),
                ('patient_name', models.CharField(max_length=255, verbose_name='ФИО пациента')),
                ('iin', models.CharField(blank=True, max_length=12, verbose_name='ИИН')),
                ('service_name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('cabinet', models.CharField(blank=True, max_length=50, verbose_name='Кабинет')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает'), ('called', 'Вызван'), ('in_progress', 'На приеме'), ('completed', 'Завершен'), ('skipped', 'Пропущен'), ('cancelled', 'Отменен')], default='waiting', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('normal', 'Обычный'), ('urgent', 'Срочный'), ('vip', 'VIP')], default='normal', max_length=20, verbose_name='Приоритет')),
                ('queue_number', models.IntegerField(verbose_name='Номер в очереди')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='Время вызова')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала приема')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_patients', to='api.doctor', verbose_name='Врач')),
                ('route_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='api.routesheet', verbose_name='Маршрутный лист')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_queues', to='api.user', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Запись очереди',
                'verbose_name_plural': 'Электронная очередь',
                'ordering': ['priority', 'queue_number', 'added_at'],
                'indexes': [models.Index(fields=['user', 'status', 'doctor'], name='api_patient_user_id_ecfabd_idx'), models.Index(fields=['status', 'queue_number'], name='api_patient_status_0deca3_idx')],
            },
        ),
    ]
