# Generated by Django 4.2.7 on 2025-12-03 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_patientqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarplan',
            name='harmful_factors',
            field=models.JSONField(default=list, help_text='Список вредных факторов для формирования приказа медкомиссии', verbose_name='Вредные факторы'),
        ),
        migrations.AddField(
            model_name='calendarplan',
            name='selected_doctors',
            field=models.JSONField(default=list, help_text='Список ID врачей, которые будут проводить осмотр', verbose_name='Выбранные врачи клиники'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма договора')),
                ('people_count', models.IntegerField(verbose_name='Количество людей подлежащих медосмотру')),
                ('execution_date', models.DateField(verbose_name='Дата исполнения договора')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_approval', 'Ожидает согласования'), ('approved', 'Согласован'), ('sent', 'Отправлен'), ('executed', 'Исполнен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('scan_files', models.JSONField(blank=True, default=list, help_text='Список путей к файлам', verbose_name='Скан-файлы договора')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('approved_by_employer_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласования работодателем')),
                ('approved_by_clinic_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласования клиникой')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата исполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_clinic', to='api.user', verbose_name='Клиника')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_employer', to='api.user', verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employer', 'clinic', 'status'], name='api_contrac_employe_885b3d_idx'), models.Index(fields=['contract_number'], name='api_contrac_contrac_6fb8d6_idx')],
            },
        ),
    ]
