# Generated by Django 4.2.7 on 2025-12-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_calendarplan_harmful_factors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='employer_bin',
            field=models.CharField(blank=True, help_text='БИН организации работодателя', max_length=20, null=True, verbose_name='БИН работодателя'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employer_phone',
            field=models.CharField(blank=True, help_text='Телефон для отправки уведомления', max_length=20, verbose_name='Телефон работодателя'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_employer', to='api.user', verbose_name='Работодатель'),
        ),
    ]
