# Generated by Django 4.2.7 on 2025-12-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_contract_employer_bin_contract_employer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_approval', 'Ожидает согласования'), ('approved', 'Согласован'), ('rejected', 'Отклонен'), ('sent', 'Отправлен'), ('executed', 'Исполнен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создан'), ('updated', 'Обновлен'), ('sent_for_approval', 'Отправлен на согласование'), ('approved', 'Согласован'), ('rejected', 'Отклонен'), ('resent_for_approval', 'Повторно отправлен на согласование'), ('cancelled', 'Отменен'), ('executed', 'Исполнен')], max_length=30, verbose_name='Действие')),
                ('user_role', models.CharField(blank=True, max_length=20, verbose_name='Роль пользователя')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий/Причина')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='Новый статус')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Детали изменений полей', verbose_name='Изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.contract', verbose_name='Договор')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История договора',
                'verbose_name_plural': 'История договоров',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', '-created_at'], name='api_contrac_contrac_b381b0_idx')],
            },
        ),
    ]
