# Generated by Django 4.2.7 on 2025-12-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_departments_info_to_calendar_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarplan',
            name='department',
            field=models.CharField(help_text='Основной объект/участок (для обратной совместимости)', max_length=255, verbose_name='Объект/участок'),
        ),
        migrations.AlterField(
            model_name='calendarplan',
            name='employee_ids',
            field=models.JSONField(default=list, help_text='Список ID всех сотрудников из всех выбранных участков', verbose_name='ID сотрудников'),
        ),
        migrations.AlterField(
            model_name='calendarplan',
            name='end_date',
            field=models.DateField(help_text='Общая дата окончания (максимальная из всех участков)', verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='calendarplan',
            name='start_date',
            field=models.DateField(help_text='Общая дата начала (минимальная из всех участков)', verbose_name='Дата начала'),
        ),
    ]
